Add Docker Build Container and Add Regtest Support
bitspill/flod pull request #1
Opened 2019-06-26 17:13 UTC by OstlerDev

# Changelog
## Added
- Docker Container for building image

## Fixed
- Regtest Network Mode

2019-06-26 17:30 UTC, cchrysostom approved these changes
These changes represent work by Medici Land Governance to provide Docker and Regtest support. The commits represent that effort accurately.

2019-08-14 16:53 UTC, cchrysostom commented
Any thoughts about this PR? I'm okay, but am a little concerned about the CI build failure.

2019-08-15 00:04 UTC, OstlerDev commented
> Any thoughts about this PR? I'm okay, but am a little concerned about the CI build failure.

The CI build failure also exists on the latest `master` code, so I figured it should be ok for it to be broken for now. We can make the CI pass if that is important.

2019-08-26 18:33 UTC, bitspill commented on wire/protocol.go
> +	TestNet BitcoinNet = 0xfabfb5da
This value appears to be reversed and should be `0xdab5bffa` as it were previously

Similar to Mainnet the bytes should appear in the other order `[3][2][1][0]` rather than `[0][1][2][3]`
Mainnet:  `0xf1a5c0fd`
```go
        pchMessageStart[0] = 0xfd;
        pchMessageStart[1] = 0xc0;
        pchMessageStart[2] = 0xa5;
        pchMessageStart[3] = 0xf1;
```


https://github.com/floblockchain/flo/blob/flo-master/src/chainparams.cpp#L388-L391
Regtest: `0xdab5bffa`
```go
        pchMessageStart[0] = 0xfa;
        pchMessageStart[1] = 0xbf;
        pchMessageStart[2] = 0xb5;
        pchMessageStart[3] = 0xda;
```

2019-08-26 18:39 UTC, bitspill requested changes
Has a go based flod been connected with a c++ based flod under the regtest network to verify interoperability?

As it stands right now I don't believe the nodes would communicate due to the wire protocol value

2019-10-24 18:49 UTC, bitspill commented
@OstlerDev Has a trial been run with the reversed pchMessageStart to see if it'll connect to the C++ regtest?

2020-01-17 02:52 UTC, merged

2020-01-18 00:13 UTC, OstlerDev commented
@bitspill Yes, a trial run was performed and with these changes it is able to connect to a FLOCore instance and download blocks. 

@metacoin performed the remaining changes, and I have reviewed and approve them.